accent = "#c4a7e7"
cursor = "#ea9a97"
foreground = "#e0def4"
background = "#232136"
selection_foreground = "#232136"
selection_background = "#ea9a97"

color0 = "#393552"
color1 = "#eb6f92"
color2 = "#3e8fb0"
color3 = "#f6c177"
color4 = "#9ccfd8"
color5 = "#c4a7e7"
color6 = "#9ccfd8"
color7 = "#e0def4"
color8 = "#6e6a86"
color9 = "#eb6f92"
color10 = "#3e8fb0"
color11 = "#f6c177"
color12 = "#9ccfd8"
color13 = "#c4a7e7"
color14 = "#9ccfd8"
color15 = "#908caa"
